### ISSUE TITLE
Issue with .ron files

### ISSUE THREAD

**Issue by P-Stringer** [KirmesBude/bevy_titan#10]
Hi,

I'm having trouble with the follow error message

```
2024-10-08T21:17:39.708883Z ERROR bevy_asset::server: Failed to load asset 'characters/characters.titan.ron' with asset loader 'bevy_titan::asset_loader::SpriteSheetLoader': Could not parse RON: 1:1: Expected opening `(` for struct `Titan`
2024-10-08T21:17:39.708886Z ERROR bevy_asset::server: Failed to load asset 'characters/characters.titan.ron' with asset loader 'bevy_titan::asset_loader::SpriteSheetLoader': Could not parse RON: 1:1: Expected opening `(` for struct `Titan`
```

`characters.titan.ron`
```
(
    textures: [
        (
            path: "male_skin_1.png",
            sprite_sheet: Homogeneous (
                tile_size: (
                    80,
                    64,
                ),
                columns: 8,
                rows: 7,
            ),
        ),
    ]
)
```

I'm using the `struct` from the example here - https://github.com/KirmesBude/bevy_titan/blob/main/examples/bevy_asset_loader.rs

and here is the list of the dependencies in my cargo file

```
[dependencies]
bevy = { version = "0.14.2", features = ["dynamic_linking"] }
bevy_asset_loader = { version = "0.21.0", features = ["2d", "standard_dynamic_assets"] }
bevy_spritesheet_animation = "0.4.2"
bevy_titan = "0.8.1"
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
```

Really not doing anything different from the example above - any ideas what the problem might be?

Thanks

**Comment by KirmesBude** [comment]
Does the bevy_asset_loader example in this repository work for you?
Otherwise maybe can you push your repository so I can check it out and test it out myself?

**Comment by P-Stringer** [comment]
Yeah, the example does work. I've attached my project. There isn't really much in it. I'm new to Rust as well as Bevy so still at the start of the learning path!

[BevySetup.zip](https://github.com/user-attachments/files/17319035/BevySetup.zip)

**Comment by P-Stringer** [comment]
I managed to fix it although I'm not sure why. I basically copied the file RON file from the example then updated the contents! Perhaps some strange encoding error...

**Comment by KirmesBude** [comment]
Yeah, looks like your original file is UTF8 BOM, which apparently contains some extra bytes in the beginning that probably trip up ron. 
Glad you were able to fix it :)
